config/routes.rb
Rails.application.routes.draw do

  
  #rutas para el search
  get 'articles/search'

  resources :categories

  # Crea una padre e hijo
  resources :articles do
    resources :comments
  end

  root 'articles#index'
  # ruta que cargara por defecto

    
  post 'contacts/new'
  
  get 'welcome/contactos'


  #Ruta para formulario contactos
  resources :contacts, only: [:create, :new]

  # Rutas para Iniciar sesion y Registrarse
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords",
  }


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article, only: [:update, :destroy, :create, :edit]

  # GET /comments
  # GET /comments.json
  def index

    redirect_to root_path
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @article.comments.new(comment_params)

    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, warning: 'Comentario Creado' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, warning: 'Comentario Actualizado' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, warning: 'Comentario Borrado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end
    def set_article
      @article = Article.find(params[:article_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:articles_id, :user_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-3">
            <fieldset>
              <%= form_with(model: [@article, @comment], local: true) do |form| %>
                <% if comment.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                    <ul>
                    <% comment.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
              <div class="form-group row">
                <%= form.text_area :body, class: "col-md-12 area-text", maxlength: 25 %>
              </div>

              <div class="form-group row">
                <%= form.submit "Crear Comentario", class: "btn btn-success" %>
              </div>
            <% end %>
            </fieldset>
    </div>                
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Articles</th>
      <th>User</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.articles %></td>
        <td><%= comment.user %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment.article %></td>
        <td><%= link_to 'Edit', article_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mt-3">
            <div class="jumbotron">
                    <fieldset>
                        <h1><%= "#{@article.title}" %></h1>
                            <%= render 'form', comment: @comment %>
                    </fieldset>
            </div>
        </div>
    </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Articles:</strong>
  <%= @comment.articles %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>