config/routes.rb
Rails.application.routes.draw do

  
  #rutas para el search
  get 'articles/search'

  resources :categories

  # Crea una padre e hijo
  resources :articles do
    resources :comments
  end

  root 'articles#index'
  # ruta que cargara por defecto

    
  post 'contacts/new'
  
  get 'welcome/contactos'


  #Ruta para formulario contactos
  resources :contacts, only: [:create, :new]

  # Rutas para Iniciar sesion y Registrarse
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords",
  }


end

app/models/article.rb
class Article < ApplicationRecord

    mount_uploader :images, ImagesUploader

    include PermissionsConcern


    has_many :has_categories
    has_many :categories, through: :has_categories, dependent: :destroy

    # articulo tiene muchos comentarios
    has_many :comments



    belongs_to :user, optional: true
        # articulos pertenece a usuario

    after_create :save_categories


        # validaciones
    validates :title, uniqueness: true
    validates :title, :body, presence: true
    validates :title, length: { maximum: 25}
    validates :body, length: { minimum: 25}
    validate :valide_categories

    #Scopes, Son busquedas en query, se usan en el controlador
    scope :ultimos, -> {order("created_at DESC")}
    # Ex:- scope :active, -> {where(:active => true)}

    scope :titulo, -> (title) { where("title LIKE ?", "#{title}%") }

        # Metodo que permite asingar valor a un atributo de un objeto
    def categories=(value)
        @categories = value 

        # raise @categories.to_yaml
    end

    def getCategories
        @categories
    end

    # Metodo para validar si esta en blanco y la categoria esta nula
    def valide_categories
        if self.getCategories.blank? && self.id.nil?
            errors.add(:categories, "Debe Agregar Una Categoria")
        end
    end

    private
        def save_categories
            @categories.each do | category_id |
                HasCategory.create(category_id: category_id, article_id: self.id)
            end
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
      # ArticlesController esta heredando de ApplicationController

  before_action :set_articles, only: [:show, :edit, :update, :destroy]
    # Solo usara el metodo set_articles donde se le indique

    before_action :authenticate_editor!, only: [:new, :create, :update, :edit]

    before_action :authenticate_admin!, only: [:destroy]

    # Metodo para hacer busquedas
  def search
    if params[:titulo]

      @articles = Article.titulo(params[:titulo])

    else

      @articles = Article.all

    end
  end

    # El index mostrara, con all, Modelo
  def index

      @articles = Article.paginate(:page => params[:page], :per_page => 2).ultimos

      # Si el usuario esta logeado y es admin mostrara esta vista
    if user_signed_in? && current_user.is_editor? && !params.has_key?(:user_normal)
    
    
      render "admin_article"

    end
  end


  def show

    #Usaremos el metodo set_articles del before_action

    @comment = Comment.new

  end



  def new

    @article = Article.new

    @categories = Category.all

  end



    # Metodo para crear
  def create
      @article = current_user.articles.new(article_params)
          # current_user = detecta si el usuario esta logeado

      @article.categories = params[:categories]

      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, warning: "Articulo Creado" }
          format.json { render :show, status: :created, location: @article}
        else
          format.html {render 'new'}
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
  end



  def edit
        # Usaremos el metodo set_articles del before_action
  end


  # Metodo para borrar
  def destroy

    #usara el set_articles, Primero

    @article.destroy

    respond_to do |format|

    format.html { redirect_to articles_path, warning: "Articulo borrado" }
    format.json { head :no_content }

    end


  end


  # Metodo para actualizar
  def update

    @article.categories = @article.categories.ids

    #usara el set_articles, Primero

    respond_to do |format|

      if @article.update(article_params)

        format.html{ redirect_to article_path, warning: "Articulo Actualizado"}
        format.json { render :show, status: :created, location: @article}

      else

        format.html { redirect_to 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }

      end
    end

  end


  

    # Metodo Reutilizable
  def set_articles
    # Si ocurre un error  
    begin
      @article = Article.find(params[:id]) 
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path, warning: "Articulo No Disponible"
    end
  end


  private
  def article_params
    params.require(:article).permit(:title, :body, :images, :categories)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="col-sm-12 col-md-6 col-lg-6 mb-2">
         <div class="card bg-light h-100">
            <%= image_tag article.images.thumb.url, class: "figure-img img-fluid rounded" %>
            <div class="card-body">
               <h5 class="card-title border-bottom pb-3"><strong><%= link_to truncate(article.title, length:20), article, class: "decoracion" %></strong>
                <a class="float-right  btn-info d-inline-flex share"></a></h5>
               <p class="card-text"><strong><%= truncate_html(article.body.html_safe, length: 250) %></strong></p>
                <%= link_to "Mostrar Articulo", article, class: "btn btn-success float-right" %>
                <% palabra = " Categorias: " %>
        <% article.categories.each do |category| %>
            <% palabra = "#{palabra} #{category.name} - " %>
            <h5>Categorias: <span class="badge badge-info"><%= category.name %></span></h5>
        <% end %> 
            </div>
         </div>
</div>

app/views/articles/_form.html.erb
<%# Esto es un formulario y un partial %>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 mt-3">
            <div class="jumbotron">
                    <fieldset>
                        <h1><%= "#{titulo} Articulo" %></h1>
                            <%= form_with(model: article, local: true) do |form| %>
                            <% if article.errors.any? %>
                                <div id="error_explanation">
                                    <h2><%= pluralize(article.errors.count, "error") %> guardando este articulo:</h2>

                                    <ul>
                                    <% article.errors.full_messages.each do |message| %>
                                        <li><%= message %></li>
                                    <% end %>
                                    </ul>
                                    </div>
                                <% end %>    
                                <div class="form-group row">     
                                    <h3><%= form.label "Titulo:", class: "col-md-6 col-form-label"%></h3>
                                    <%= form.text_field :title, class: "col-md-6", maxlength: 25 %>
                                </div>
                                
                                <div class="form-group row">
                                    <h3 class="muevelo"><%= form.label "Cuerpo:", class: "col-md-6 col-form-label"%></h3>
                                    <%= form.text_area :body, minlength: 25, class: "area-text col-md-6" %>
                                </div>

                                <div class="form-group">
                                    <%= form.file_field :images %>
                                </div>

                                <% Category.all.each do |category| %>
                                    <%= check_box_tag "categories[]", category.id%>
                                        <%# categories[] = es como un arreglo permite guardar mas id  %>
                                    <%= category.name %><br>
                                <% end %>

                                <div class="form-group">
                                    <%= form.submit "Enviar", class: "btn btn-success btn-lg col-md-3"%>
                                    <%= link_to 'Atras', root_path, class: "btn btn-secondary btn-lg col-md-3" %>
                                </div>
                            <%end%>
                    </fieldset>
            </div>
        </div>
    </div>
</div>

app/views/articles/admin_article.html.erb
<div class="jumbotron table-responsive">
<h1>Administrador</h1>
<%= link_to "Normal", articles_path(user_normal:true), class: "btn btn-success mb-3" %>
    <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Titulo:</th>
                    <th>Fecha De Creacion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="bg-info">
                <% @articles.each do |arti| %>
                    <tr class="text-center">
                        <td ><%= arti.id %></td>
                        <td ><%= arti.title %></td>
                        <td ><%= arti.created_at.strftime('%b, %d, %Y') %></td>

                        <td>
                            <%= link_to "Ver", arti, class: "btn btn-info text-center"%>
                            <%= link_to "Editar", edit_article_path(arti), class: "btn btn-warning text-center" %>
                            <%= link_to "Eliminar", arti, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger text-center"  %>
                        </td>

                    </tr>
                <% end %>
            </tbody>

    </table>
    
</div>
<div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
    <%= will_paginate @articles %>
    </div>

app/views/articles/edit.html.erb
<%= render "form", article: @article, titulo: "Editar" %>
    <%# Esta renderizando y usando el partial _form %>

app/views/articles/index.html.erb
<div class="container-fluid">
    <div class="row">
        <%= render @articles %>
    </div>
    <div class="flickr_pagination" style="margin-top: 20px; margin-bottom: 20px;">
    <%= will_paginate @articles %>
    </div>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article, titulo: "Agregar Nuevo" %>
    <%# Esta renderizando y usando el partial _form %>

app/views/articles/search.html.erb
<div class= "jumbotron">
    <div class="row">
        <% unless @articles.blank? %>
            <% @articles.each do |art| %>
                <div class="col-md-6">
                    <h1><%= link_to art.title, art, class: "decoracion" %></h1>
                    <p><%= truncate_html(art.body, length: 400)  %><p>
                    <p><%= link_to "Ver Mas", art, class: "btn btn-success"%><p>

                </div>
            <% end %>
        <% else %>
            <h2>No Existe Busqueda</h2>
        <% end %>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-10 mb-2">
         <div class="card bg-light mb-3">
            <%= image_tag @article.images.thumb.url, class: "figure-img img-fluid rounded" %>
            <div class="card-body">
               <h5 class="card-title border-bottom pb-3"><strong><%= @article.title %></strong>
                <a class="float-right  btn-info d-inline-flex share"></a></h5>
               <p class="card-text"><strong><%= truncate_html(@article.body.html_safe, length: 250) %></strong></p>
                <% palabra = " Categorias: " %>
                    <% @article.categories.each do |category| %>
                        <% palabra = "#{palabra} #{category.name} - " %>
                        <h5>Categorias: <span class="badge badge-info"><%= category.name %></span></h5>
                    <% end %>
                    <% if user_signed_in? %>
                        <%= render "comments/form", comment: @comment%>
                    <% end %>

                    <ul>
                        <% @article.comments.each do |comment| %>
                            <li>
                                <div class="row mt-3">
                                    <div class="col-md-4">
                                        <%= comment.body %>
                                    </div>
                                    <div class="col-md-4">
                                        <% if user_signed_in? && current_user == comment.user %>
                                            <%= link_to "Editar" , edit_article_comment_url(@article, comment), class: "btn btn-info"%>
                                            <%= link_to "Eliminar", [@article,comment], method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-warning"%>
                                        <% end %>
                                    </div>
                                </div>
                            </li>
                        <% end %>
                    </ul>

         </div>

        </div>


    </div>
</div>