config/routes.rb
Rails.application.routes.draw do

  
  #rutas para el search
  get 'articles/search'

  resources :categories

  # Crea una padre e hijo
  resources :articles do
    resources :comments
  end

  root 'articles#index'
  # ruta que cargara por defecto

    
  post 'contacts/new'
  
  get 'welcome/contactos'


  #Ruta para formulario contactos
  resources :contacts, only: [:create, :new]

  # Rutas para Iniciar sesion y Registrarse
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords",
  }


end

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Klk WaWaWa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Inicio", root_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Contacto", new_contact_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
        <%if user_signed_in?%>
          <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <%else%>
          <li><%= link_to "Inicia Sesion", new_user_session_path, class: "nav-link" %></li>
          <%= link_to "Registrarte Ahora", new_user_registration_path, class: "nav-link" %>
        <%end%>
      </li>
    </ul>

    <%= form_tag articles_search_path, :method => 'get', class: "form-inline my-2 my-lg-0" do %>
       <%= text_field_tag :titulo, params[:titulo], placeholder: "Buscar", class: "form-control mr-sm-2" %>
      <%= submit_tag 'Buscar', :name => nil, class: "btn btn-info my-2 my-sm-0"  %>
    <% end %>
  </div>
</nav>

app/views/partials/_notificaciones.html.erb
<% flash.each do |name, msg| %>
      <div class="alert alert-dismissible alert-<%= name %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading"><%= msg %></h4>
      </div>
    <%end%>

app/views/partials/_panel.html.erb
<% if user_signed_in? %>
    <% if current_user.is_admin?  %>
        <div class="list-group">
            <%= link_to "Administrador", articles_path, class: "list-group-item list-group-item-action active bg-primary " %>
            <%= link_to "Ver Articulos", articles_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "Nuevo Articulo", new_article_path, class: "list-group-item list-group-item-action bg-info text-white"%>
            <%= link_to "Ver Categorias", categories_path, class: "list-group-item list-group-item-action" %>
            <%= link_to "Nueva Categoria", new_category_path, class: "list-group-item list-group-item-action bg-success text-white"%>
        </div>
    <% end%>
<% end %>


<div class="list-group">
  <%= link_to "Categorias", categories_path, class: "list-group-item list-group-item-action active" %>
    <% Category.all.each do |category| %>
        <%= link_to category.name, category, class: "list-group-item list-group-item-action" %>
    <%end%>
</div>