config/routes.rb
Rails.application.routes.draw do

  
  #rutas para el search
  get 'articles/search'

  resources :categories

  # Crea una padre e hijo
  resources :articles do
    resources :comments
  end

  root 'articles#index'
  # ruta que cargara por defecto

    
  post 'contacts/new'
  
  get 'welcome/contactos'


  #Ruta para formulario contactos
  resources :contacts, only: [:create, :new]

  # Rutas para Iniciar sesion y Registrarse
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    passwords: "users/passwords",
  }


end

app/models/category.rb
class Category < ApplicationRecord

    mount_uploader :images, ImagesUploader



    # tiene muchos articles
    has_many :has_categories
    has_many :articles, through: :has_categories

    belongs_to :user, optional: true
     # Pertenece a user

     validates :name, :color, presence: true
     validates :name, length: { in: 7..20 }
     validates :color, length: { in: 4..7 }
        # validaciones
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_editor!, only: [:new, :create, :update, :edit]

  before_action :authenticate_admin!, only: [:destroy]



  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    if user_signed_in? && current_user.is_editor? && !params.has_key?(:user_normal)
    
    
      render "admin_category"

    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, warning: 'Categoria creada.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, warning: 'Categoria actualizada.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, warning: 'Categoria borrada.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
        @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, warning: "Categoria No Encontrada"
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<style type="text/css" media="screen">
  <%= ".#{category.name}" %> {
    background: <%= category.color %> !important ;
  }

</style>

<div class="col-md-6">
    <div class="jumbotron <%= "#{category.name}" %>">
        <h2><%= category.name %></h2>
        <%= image_tag category.images.thumb.url, class: "figure-img img-fluid rounded" %>
        <h4><%= "Contiene #{category.articles.count} articulo (s)" %></h4>
       
    </div>
</div> 

app/views/categories/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 mt-3">
      <div class="jumbotron">
        <h1><%= "#{title} Categoria"%></h1>
        <%= form_with(model: category, local: true) do |form| %>
          <% if category.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(category.errors.count, "error") %> guardando esta categoria:</h2>

              <ul>
              <% category.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group row">
            <h3><%= form.label "Name:", class: "col-md-6 col-form-label"%></h3>
            <%= form.text_field :name, id: :category_name, class:"col-md-6" %>
          </div>

          <div class="form-group row">
            <h3><%= form.label "Color:", class: "col-md-6 col-form-label"%></h3>
            <%= form.color_field :color, id: :category_color, class:"col-md-6" %>
          </div>

          <div class="form-group row">
            <%= form.submit "Enviar", class: "btn btn-success btn-lg col-md-3" %>
            <%= link_to 'Atras', @category, class: "btn btn-secondary btn-lg col-md-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/categories/admin_category.html.erb
<div class="jumbotron">
<h1>Administrador</h1>
<%= link_to "Normal", categories_path(user_normal:true), class: "btn btn-success mb-3" %>
    <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th>Titulo:</th>
                    <th>Fecha De Creacion</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="bg-info">
                <% @categories.each do |catego| %>
                    <tr class="text-center">
                        <td ><%= catego.name %></td>
                        <td ><%= catego.created_at.strftime('%b, %d, %Y') %></td>

                        <td>
                            <%= link_to "Ver", catego, class: "btn btn-info text-center"%>
                            <%= link_to "Editar", edit_category_path(catego), class: "btn btn-warning text-center" %>
                            <%= link_to "Eliminar", catego, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger text-center"  %>
                        </td>

                    </tr>
                <% end %>
            </tbody>

    </table>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category, title: "Editar" %>

app/views/categories/index.html.erb
<div class="row">
  <%= render @categories %>
</div>

app/views/categories/new.html.erb
<%= render 'form', category: @category, title: "Agregar Nueva"%>

app/views/categories/show.html.erb
<style type="text/css" media="screen">
  .jumbotron {
    margin-top: 10px;
  }

  .categories-show {
        background: <%= @category.color %> !important ;
        height: 5rem;

  }

</style>
<div class="categories-show">

  <h2 class="text-center"> <%= @category.name %> </h2>
    <h5>

    <% if !@category.user.nil? %>
      <p class="mb-3 text-center">Creado por <strong><%= @category.user.email %></strong></p>
      
    <% end %>
    </h5>
</div>
  <div class="row mt-3">
    <% @category.articles.each do |article|%>

    <div class="col-sm-12 col-md-6 col-lg-6 mb-2">
            <div class="card bg-light h-100">
                <%= image_tag article.images.thumb.url, class: "figure-img img-fluid rounded" %>
                <div class="card-body">
                  <h5 class="card-title border-bottom pb-3"><strong><%= link_to truncate(article.title, length:20), article, class: "decoracion" %></strong>
                    <a class="float-right  btn-info d-inline-flex share"></a></h5>
                  <p class="card-text"><strong><%= truncate_html(article.body.html_safe, length: 250) %></strong></p>

                    <% if user_signed_in? && current_user.is_admin? %>
            <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-warning" %>
            <%= link_to 'Eliminar', category_path(@category), method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-danger"%>
                  <% end %>
                    <%= link_to "Mostrar Articulo", article, class: "btn btn-info" %>
                    <%= link_to 'Back', categories_path, class: "btn btn-success float-right" %>

                   <div class="mt-3">
                     <% palabra = " Categorias: " %>
            <% article.categories.each do |category| %>
                <% palabra = "#{palabra} #{category.name} - " %>
            <% end %> 
            <p><%= palabra %></p>
                   </div>
                </div>
            </div>
    </div>

     
    
    <% end %>

  
  </div>
 
    



  